/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appDataSchema as googlecalendar_zod_ts } from "./googlecalendar/zod";

export const appDataSchemas = {
  googlecalendar: googlecalendar_zod_ts,
};
